
window.SUPABASE_URL = "https://ftcsrejkyfslahhfjkci.supabase.co";
window.SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZ0Y3NyZWpreWZzbGFoaGZqa2NpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzY2NjIwMTMsImV4cCI6MjA5MjIzODAxM30.z-6LPc9VbpOXTw9zquX8whgm4YGYth0pEdbqe11z0tU";
